### ISSUE TITLE
CLI to replace vit-kedqr

### ISSUE THREAD

**Issue by mzabaluev** [input-output-hk/vit-testing#21]
The functionality in [vit-kedqr](https://github.com/input-output-hk/vit-kedqr) a Go-based tool used to test Catalyst the app,
should be incorporated into the tools in this Rust project. Most of the implementation has been done by @enzoc4, it just needs a CLI and some glue logic.

**Comment by dkijania** [comment]
`Vit-kedqr`  project is a production component which enable qr code generation for those users who want to register themselves via `vit-registration-tool` cli rather than use Daedalus UI. 

Initial implementation was written in go as a interim solution. We would like to keep our code in rust to easily use it in tests as a library but also as a cli tool with the same functionality.

Rust implementaion is here:

https://github.com/input-output-hk/jormungandr/blob/master/testing/jormungandr-testing-utils/src/qr_code.rs

The idea i would like to pursue is that `qr_code`  module would be reused in tests and in production code, so it can be a separate project. Then we would work on adjusting jormungandr and vit-testing code to reuse `vit-kedqr` in tests
